### PR TITLE
Added DataStreams based Source and streaming

### LINKED ISSUE #28: Set column types in DataFrames.readtable
Unfortunately the function DataFrames.readtable returns a DataFrame with all columns being type Any. This requires type conversions for building subsets.
e.g.
    df = DataFrames.readtable( ....."select year,dest,sum(import_val) as imp from .....
    df[:year] = map(x -> isna(x) ? NA : convert(Int16, x), df[:year])
    dfy = df[df[:year].==1980, :] # subset for year 1980

I would appreciate a modiefied Funktion which sets column types. I am not Julia expert, so the following  suggestion might be of limited use.

```julia
@require DataFrames begin
using DataFrames
function DataFrames.readtable(rs::JResultSet)
    rsmd = getMetaData(rs)
    cols = getColumnCount(rsmd)
    columns = Array{Any}(cols)
    missings = Array{Any}(cols)
    cnames = Array{Symbol}(cols)
    get_methods = Array{Function}(cols)
    for c in 1:cols
        cty = getColumnType(rsmd,c)
        if cty==JDBC_COLTYPE_SMALLINT
            columns[c] = Array{Int16}(0)
        elseif cty==JDBC_COLTYPE_INTEGER
            columns[c] = Array{Int32}(0)
        elseif cty==JDBC_COLTYPE_BIGINT
            columns[c] = Array{Int64}(0)
        elseif cty==JDBC_COLTYPE_VARCHAR
            columns[c] = Array{String}(0)
        elseif cty in [JDBC_COLTYPE_REAL,JDBC_COLTYPE_FLOAT,JDBC_COLTYPE_DOUBLE,JDBC_COLTYPE_DECIMAL]
            columns[c] = Array{Float64}(0)
        else
            columns[c] = Array{Any}(0)
        end
        missings[c] = Array{Bool}(0)
        cnames[c] = DataFrames.makeidentifier(getColumnName(rsmd, c))
        get_methods[c] = jdbc_get_method(getColumnType(rsmd, c))
    end
    for r in rs
        for c in 1:cols
            push!(columns[c], get_methods[c](rs, c))
            if wasNull(rs)
                push!(missings[c], true)
            else
                push!(missings[c], false)
            end
        end
    end

    dcolumns = Array{Any}(cols)

    for c in 1:cols
        dcolumns[c] = DataArrays.DataArray(columns[c], missings[c])
    end
    return DataFrame(dcolumns, cnames)
end
end #@require
```

### PR DESCRIPTION
**Pull request by ExpandingMan**
This adds a DataStreams based source object and methods needed for streaming.  Also fixes #28 and some import conflict warnings with DBAPI.

Please note that although I tested this I was not actually able to run `runtests.jl`, as it always throws various Derby errors (seemingly unrelated to changes in this PR).

### CODE REVIEW

**Comment by ExpandingMan** [comment]
Getting the following error
```
ERROR: LoadError: MethodError: no method matching readtable(::JavaCall.JavaObject{Symbol("java.sql.ResultSet")})
```
on 0.5.  Not sure why this would happen, any ideas?  0.6 seems fine.

**Comment by aviks** [comment]
Thanks a ton. I'll test this shortly.

**Comment by aviks** [comment]
In general, I'm happy to drop 0.5 support at this point.

**Comment by ExpandingMan** [comment]
If you're willing I'll take out all of the stuff for version < 0.6 tomorrow morning.  I'm not in front of a development environment at the moment.

**Comment by aviks** [comment]
Sure thing, thanks!

**Comment by ExpandingMan** [comment]
Ok, I have dropped 0.5 support.  I've also gone in and removed `Compat` and all `@compat` macros entirely, as they are no longer necessary.

**Comment by ExpandingMan** [comment]
I've also added a `JDBC.Source` constructor and a `readtable` method for the DBAPI cursor so that using the DBAPI is a little more user friendly.

By the way, it would be *really* nice to be able to actually run the tests on this but I absolutely can't figure out why Java throws all these errors when it tries to load derby.  Is there something obvious that I'm missing there?

I was thinking about making the use of JDBC drivers more user friendly as well, but I'm worried there will be all sorts of licensing legal nonsense if I include jar files in the repo.

**Comment by aviks** [comment]
Re tests: Not sure. The derby jars are included in this repo, so it should be pretty simple. The tests pass on travis, as you will have seen. What kind of errors are you getting? 

Re drivers, it may make sense to include open source drivers in this repo, but we obviously can't add proprietary drivers into the repo. 

Thanks again for taking care of  this, I really appreciate it.

**Comment by quinnj** [comment]
Great stuff @ExpandingMan !

**Comment by ExpandingMan** [comment]
Thanks.  And thanks for all the improvements to the DataStreams interface, setting up the source for JDBC went very smoothly.

**Pull request merged**
